# Copyright Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  workflow_call:
    inputs:
      build-podman-release:
        required: false
        type: boolean

jobs:
  podman_release_build_via_makefile:
    name: Release build using Podman and Makefile
    if: ${{ inputs.build-podman-release }}
    runs-on: ubuntu-latest
    # Default: 360 minutes
    timeout-minutes: 45

    steps:
      - name: Check out code (full history)
        uses: actions/checkout@v3.5.3
        with:
          # Full history is needed to allow listing tags via build tooling
          # (e.g., go-winres, git-describe-semver)
          fetch-depth: 0

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      - name: Mark the current working directory as a safe directory in git
        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        run: git config --global --add safe.directory "${PWD}"

      - name: Use Podman to generate release build assets
        run: make podman-release-build
