# Copyright Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  workflow_call:
    inputs:
      build-packages:
        required: false
        type: boolean
        default: true

jobs:
  # https://stackoverflow.com/questions/76151411/use-github-actions-to-check-if-branch-is-up-to-date-with-main
  # https://stackoverflow.com/a/76151412/903870
  # https://github.com/atc0005/shared-project-resources/issues/135
  assert_pr_branch_is_ahead_of_primary_branch:
    name: Assert PR branch is ahead of primary
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code (full history)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3.5.3
        with:
          # Full history is needed to allow listing tags via build tooling
          # (e.g., go-winres, git-describe-semver)
          fetch-depth: 0

      - name: Check if branch is ahead of master
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if ! git merge-base --is-ancestor origin/master ${{ github.event.pull_request.head.sha }};
          then echo "This branch is not up to date with primary branch";
          exit 1; fi

  build_packages_via_makefile:
    name: Build packages using Makefile
    if: ${{ inputs.build-packages }}
    runs-on: ubuntu-latest
    # Default: 360 minutes
    #
    # The check-vmware project requires more time than the others, so we use
    # that projects build time as the max runtime for this workflow for all
    # projects.
    timeout-minutes: 55
    container:
      # Use current/stable Go build image as our build environment instead of
      # directly in the runner environment; our build image provides all
      # tooling needed to generate packages.
      image: "ghcr.io/atc0005/go-ci:go-ci-stable-build"

    steps:
      - name: Print go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.5.3

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      - name: Mark the current working directory as a safe directory in git
        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        run: git config --global --add safe.directory "${PWD}"

      - name: Build packages
        run: make packages
