# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  workflow_call:

# https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow
env:
  # https://github.com/atc0005/go-ci/issues/848
  #
  # Confirmed working:
  # GO_CI_IMG_RELEASE_VER: "v0.7.9-0-gdf9564d3"
  #
  # Without workarounds will fail (git package security updates):
  # GO_CI_IMG_RELEASE_VER: "v0.7.10-0-gcc0a2418"
  #
  # Use latest atc0005/go-ci image releases, trusting that workarounds applied
  # in this workflow are sufficient to resolve any issues not handled in the
  # image itself:
  GO_CI_IMG_RELEASE_VER: "latest"

jobs:
  dependency_updates:
    name: Look for available minor or patch releases
    runs-on: ubuntu-latest

    # Mark just this one job as failed, not the whole workflow.
    continue-on-error: true
    timeout-minutes: 10
    container:
      image: "ghcr.io/atc0005/go-ci:go-ci-lint-only-${{ env.GO_CI_IMG_RELEASE_VER }}"

    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      - name: Mark the current working directory as a safe directory in git
        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        run: git config --global --add safe.directory "${PWD}"

      # Provided for contrast. Will likely remove this one at some point.
      - name: go list
        run: |
          go list -mod=mod -u -f '{{if .Update}}{{.Path}}: {{.Version}} -> {{.Update.Version}} ({{.Update.Time}}){{end}}' -m all
          # go list -mod=mod -u -m all
          # go list -mod=mod -u -json -m all

      - name: go get
        run: |
          go get -u ./...
          go mod tidy
          git diff --exit-code go.???
