# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  workflow_call:

jobs:
  dependency_updates:
    name: Look for available minor or patch releases
    runs-on: ubuntu-latest

    # Mark just this one job as failed, not the whole workflow.
    continue-on-error: true
    timeout-minutes: 10
    container:
      image: ghcr.io/atc0005/go-ci:go-ci-lint-only-v0.7.9-0-gdf9564d3

    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0

      # Provided for contrast. Will likely remove this one at some point.
      - name: go list
        run: |
          go list -mod=mod -u -f '{{if .Update}}{{.Path}}: {{.Version}} -> {{.Update.Version}} ({{.Update.Time}}){{end}}' -m all
          # go list -mod=mod -u -m all
          # go list -mod=mod -u -json -m all

      - name: go get
        run: |
          go get -u ./...
          go mod tidy
          git diff --exit-code go.???
