# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  workflow_call:

jobs:
  go_mod_changes:
    name: Look for missing go.mod changes
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: "ghcr.io/atc0005/go-ci:go-ci-stable-mirror-build"

    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.0

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      - name: Mark the current working directory as a safe directory in git
        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        run: git config --global --add safe.directory "${PWD}"

      - name: go mod tidy
        run: |
          go mod tidy -v
          git diff --exit-code go.mod

  go_mod_vendor:
    name: Look for missing vendored dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: "ghcr.io/atc0005/go-ci:go-ci-stable-mirror-build"

    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.0

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      - name: Mark the current working directory as a safe directory in git
        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        run: git config --global --add safe.directory "${PWD}"

      - name: go mod vendor
        run: |
          go mod vendor
          git diff --exit-code
