# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  workflow_call:

# https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow
env:
  # https://github.com/atc0005/go-ci/issues/848
  #
  # Confirmed working:
  # GO_CI_IMG_RELEASE_VER: "v0.7.9-0-gdf9564d3"
  #
  # Without workarounds will fail (git package security updates):
  # GO_CI_IMG_RELEASE_VER: "v0.7.10-0-gcc0a2418"
  #
  # Use latest atc0005/go-ci image releases, trusting that workarounds applied
  # in this workflow are sufficient to resolve any issues not handled in the
  # image itself:
  GO_CI_IMG_RELEASE_VER: "latest"

jobs:
  go_mod_changes:
    name: Look for missing go.mod changes
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: "ghcr.io/atc0005/go-ci:go-ci-lint-only-${{ env.GO_CI_IMG_RELEASE_VER }}"

    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0

      - name: go mod tidy
        run: |
          go mod tidy -v
          git diff --exit-code go.mod

  go_mod_vendor:
    name: Look for missing vendored dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: "ghcr.io/atc0005/go-ci:go-ci-lint-only-${{ env.GO_CI_IMG_RELEASE_VER }}"

    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0

      - name: go mod vendor
        run: |
          go mod vendor
          git diff --exit-code
