# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  pull_request:
    types: [opened, synchronize]
  workflow_call:

jobs:
  lint_markdown:
    name: Lint Markdown files
    runs-on: "ubuntu-latest"
    # Default: 360 minutes
    timeout-minutes: 10

    steps:
      - name: Setup Node
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "lts/*"

      - name: Install Markdown linting tools
        run: |
          npm install markdownlint --save-dev
          npm install -g markdownlint-cli
          echo "markdownlint version: $(markdownlint --version)"

      - name: Check out code
        uses: actions/checkout@v3.5.1

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      - name: Mark the current working directory as a safe directory in git
        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        run: git config --global --add safe.directory "${PWD}"

      - name: Run Markdown linting tools
        # The `.markdownlint.yml` file specifies config settings for this
        # linter, including which linting rules to ignore.
        #
        # Note: Explicitly ignoring top-level vendor folder; we do not want
        # potential linting issues in bundled documentation to fail linting CI
        # runs for *our* documentation
        run: |
          echo "markdownlint version: $(markdownlint --version)"
          markdownlint '**/*.md' --ignore node_modules --ignore vendor

  lint_dockerfiles:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/hadolint/hadolint:latest-debian

    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.1

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      #- name: Mark the current working directory as a safe directory in git
      #  # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      #  run: git config --global --add safe.directory "${PWD}"

      - name: Run hadolint against any Dockerfiles
        if: hashFiles('**/Dockerfile') != ''
        run: |
          hadolint --version
          find  . -name "Dockerfile" -print -exec hadolint {} \;
