# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  workflow_call:
    inputs:
      os-dependencies:
        required: false
        type: string
      gogeninstall:
        required: false
        type: boolean

# https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow
env:
  # https://github.com/atc0005/go-ci/issues/848
  #
  # Confirmed working:
  # GO_CI_IMG_RELEASE_VER: "v0.7.9-0-gdf9564d3"
  #
  # Without workarounds will fail (git package security updates):
  # GO_CI_IMG_RELEASE_VER: "v0.7.10-0-gcc0a2418"
  #
  # Use latest atc0005/go-ci image releases, trusting that workarounds applied
  # in this workflow are sufficient to resolve any issues not handled in the
  # image itself:
  GO_CI_IMG_RELEASE_VER: "latest"

jobs:
  lint_code_with_makefile:
    name: Lint codebase using Makefile
    runs-on: ubuntu-latest
    # Default: 360 minutes
    timeout-minutes: 10
    container:
      # Use (lightly touched) mirror of current "vanilla" upstream golang image
      image: "ghcr.io/atc0005/go-ci:go-ci-stable-mirror-build-${{ env.GO_CI_IMG_RELEASE_VER }}"

    steps:
      - name: Print go version
        run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.3.0

      # bsdmainutils provides "column" which is used by the Makefile
      - name: Install Ubuntu packages
        run: apt-get update && apt-get install -y --no-install-recommends make gcc bsdmainutils

      - name: Install Go linting tools
        run: make lintinstall

      # NOTE: We are intentionally *not* removing the repo-provided config
      # file as this workflow is intended to emulate running the Makefile via
      # a local dev environment.
      #
      # - name: Remove repo-provided golangci-lint config file
      #   run: |
      #     # Remove the copy of the config file bundled with the repo/code so
      #     # that the configuration provided by the atc0005/go-ci project is
      #     # used instead
      #     rm -vf .golangci.yml

      - name: Run Go linting tools using project Makefile
        run: make linting

  build_code_with_makefile_all_recipe:
    name: Build codebase using Makefile all recipe
    runs-on: ubuntu-latest
    # Default: 360 minutes
    #
    # The check-vmware project requires more time than the others, so we use
    # that projects build time as the max runtime for this workflow for all
    # projects.
    timeout-minutes: 55
    container:
      # Use (lightly touched) mirror of current "vanilla" upstream golang image
      image: "ghcr.io/atc0005/go-ci:go-ci-stable-mirror-build-${{ env.GO_CI_IMG_RELEASE_VER }}"

    steps:
      - name: Print go version
        run: go version

      - name: Check out code into the Go module directory (single commit)
        if: inputs.gogeninstall == false
        uses: actions/checkout@v3.3.0

      - name: Check out code into the Go module directory (full history)
        if: inputs.gogeninstall
        uses: actions/checkout@v3.3.0
        with:
          # Needed in order to retrieve tags for use with go generate
          fetch-depth: 0

      - name: Install Ubuntu packages (standard set)
        if: ${{ inputs.os-dependencies == '' }}
        # bsdmainutils provides "column" which is used by the Makefile
        run: apt-get update && apt-get install -y --no-install-recommends make gcc bsdmainutils xz-utils

      - name: Install Ubuntu packages (custom set)
        if: ${{ inputs.os-dependencies != '' }}
        run: apt-get update && apt-get install -y --no-install-recommends ${{ inputs.os-dependencies }}

      - name: Install go generate dependencies (if requested)
        if: inputs.gogeninstall
        run: make gogeninstall

      - name: Build using project Makefile
        run: make all
