# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  workflow_call:
    inputs:
      default-repo:
        required: false
        type: string
        default: origin
      primary-branch:
        required: false
        type: string
        default: master
      development-branch:
        required: false
        type: string
        default: development
      fetch-depth:
        required: false
        type: number
        default: 50

jobs:
  # https://stackoverflow.com/questions/76151411/use-github-actions-to-check-if-branch-is-up-to-date-with-main
  # https://stackoverflow.com/a/76151412/903870
  # https://github.com/atc0005/shared-project-resources/issues/135
  assert_pr_branch_is_ahead_of_primary_branch:
    name: Assert PR branch is ahead
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code (subset)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3.6.0
        with:
          # Retrieve sufficient amount of history (along with tags) to allow
          # build tooling (e.g., go-winres, git-describe-semver) to processing
          # tags as part of asset generation tasks.
          fetch-depth: ${{ inputs.fetch-depth }}
          fetch-tags: true

      - name: Fetch additional references
        run: |
          git fetch origin ${{ inputs.primary-branch }} --depth 50
          git fetch origin ${{ inputs.development-branch }} --depth 50

      - name: Assert source branches are set
        run: |
          abort="false"
          if [[ "${{ format('{0}/{1}', inputs.default-repo, inputs.primary-branch) }}" == "/" ]] ; then \
            echo "default repo and primary branch values not set!"; abort="true"; fi

          if [[ "${{ format('{0}/{1}', inputs.default-repo, inputs.development-branch) }}" == "/" ]] ; then \
            echo "default repo and development branch values not set!"; abort="true"; fi

          if [[ "$abort" == "true" ]]; then exit 1; fi

          echo "Primary branch: ${{ format('{0}/{1}', inputs.default-repo, inputs.primary-branch) }}"
          echo "Development branch: ${{ format('{0}/{1}', inputs.default-repo, inputs.development-branch) }}"

      - name: Assert PR branch is ahead of acceptable source branches
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if ! (git merge-base --is-ancestor ${{ format('{0}/{1}', inputs.default-repo, inputs.primary-branch) }} ${{ github.event.pull_request.head.sha }} || \
            git merge-base --is-ancestor ${{ format('{0}/{1}', inputs.default-repo, inputs.development-branch) }} ${{ github.event.pull_request.head.sha }});
          then echo "This branch is not up to date with ${{ inputs.primary-branch }} or ${{ inputs.development-branch }} branches!";
          exit 1; fi

  lint_code:
    needs: assert_pr_branch_is_ahead_of_primary_branch
    name: Lint codebase
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Don't flag the whole workflow as failed if "experimental" matrix jobs
    # fail. This allows the unstable image linting tasks to fail without
    # marking the oldstable and stable image linting jobs as failed.
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      # Don't stop all workflow jobs if the unstable image linting tasks fail.
      fail-fast: false
      matrix:
        container-image: ["go-ci-oldstable", "go-ci-stable"]
        experimental: [false]
        include:
          - container-image: "go-ci-unstable"
            experimental: true
    container:
      image: "ghcr.io/atc0005/go-ci:${{ matrix.container-image}}"

    steps:
      - name: Check out code
        uses: actions/checkout@v3.6.0

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      - name: Mark the current working directory as a safe directory in git
        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        run: git config --global --add safe.directory "${PWD}"

      - name: Remove repo-provided golangci-lint config file
        run: |
          # Remove the copy of the config file bundled with the repo/code so
          # that the configuration provided by the atc0005/go-ci project is
          # used instead
          rm -vf .golangci.yml

      - name: Run golangci-lint using container-provided config file settings
        run: |
          golangci-lint --version

          # Override default timeout to accomodate more complex (or CGO)
          # codebases which take longer to lint.
          golangci-lint run --timeout=5m

      # This is the very latest stable version of staticcheck provided by the
      # atc0005/go-ci container. The version included with golangci-lint often
      # lags behind the official stable releases.
      - name: Run staticcheck
        run: |
          staticcheck --version
          staticcheck $(go list -mod=vendor ./... | grep -v /vendor/)

  optional_linting:
    needs: assert_pr_branch_is_ahead_of_primary_branch
    name: Optional Linting
    uses: atc0005/shared-project-resources/.github/workflows/lint-using-optional-linters.yml@master

  test_code:
    needs: assert_pr_branch_is_ahead_of_primary_branch
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Don't flag the whole workflow as failed if "experimental" matrix jobs
    # fail. This allows unstable image tests to fail without marking the
    # oldstable and stable image jobs as failed.
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      # Don't stop all workflow jobs if the unstable image tests fail.
      fail-fast: false
      matrix:
        container-image: ["go-ci-oldstable", "go-ci-stable"]
        experimental: [false]
        include:
          - container-image: "go-ci-unstable"
            experimental: true
    container:
      image: "ghcr.io/atc0005/go-ci:${{ matrix.container-image}}"

    steps:
      - name: Check out code
        uses: actions/checkout@v3.6.0

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      - name: Mark the current working directory as a safe directory in git
        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        run: git config --global --add safe.directory "${PWD}"

      - name: Run all tests
        run: go test -mod=vendor -v ./...

  build_code:
    needs: assert_pr_branch_is_ahead_of_primary_branch
    name: Build codebase
    runs-on: ubuntu-latest
    # Default: 360 minutes
    timeout-minutes: 10
    # Don't flag the whole workflow as failed if "experimental" matrix jobs
    # fail. This allows unstable image build tasks to fail without marking the
    # oldstable and stable image jobs as failed.
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      # Don't stop all workflow jobs if the unstable image build tasks fail.
      fail-fast: false
      matrix:
        container-image: ["go-ci-oldstable", "go-ci-stable"]
        experimental: [false]
        include:
          - container-image: "go-ci-unstable"
            experimental: true
    container:
      image: "ghcr.io/atc0005/go-ci:${{ matrix.container-image}}"

    steps:
      - name: Print go version
        run: go version

      - name: Check out code
        uses: actions/checkout@v3.6.0

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      - name: Mark the current working directory as a safe directory in git
        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        run: git config --global --add safe.directory "${PWD}"

      - name: Build using vendored dependencies
        # NOTE: This will fail if there is a doc.go file in the project root
        # with a message similar to:
        #
        # # github.com/atc0005/check-cert
        # runtime.main_main·f: function main is undeclared in the main package
        run: go build -v -mod=vendor ./...
