# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  workflow_call:

jobs:
  lint_and_test_code:
    name: Lint and test using latest stable container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/atc0005/go-ci:go-ci-lint-only

    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0

      - name: Remove repo-provided golangci-lint config file
        run: |
          # Remove the copy of the config file bundled with the repo/code so
          # that the configuration provided by the atc0005/go-ci project is
          # used instead
          rm -vf .golangci.yml

      - name: Run golangci-lint using container-provided config file settings
        run: |
          golangci-lint --version
          golangci-lint run

      - name: Run all tests
        run: go test -mod=vendor -v ./...

  go_mod_changes:
    name: Look for uncommitted Go module changes
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/atc0005/go-ci:go-ci-lint-only

    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0

      - name: go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod

      - name: go mod vendor
        run: |
          go mod vendor
          git diff --exit-code

  go_get_update_changes:
    name: Look for available minor or patch releases
    runs-on: ubuntu-latest

    # Mark just this one job as failed, not the whole workflow.
    continue-on-error: true
    timeout-minutes: 10
    container:
      image: ghcr.io/atc0005/go-ci:go-ci-lint-only

    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0

      # Provided for contrast. Will likely remove this one at some point.
      - name: go list
        run: |
          go list -mod=mod -u -f '{{if .Update}}{{.Path}}: {{.Version}} -> {{.Update.Version}} ({{.Update.Time}}){{end}}' -m all
          # go list -mod=mod -u -m all
          # go list -mod=mod -u -json -m all

      - name: go get
        run: |
          go get -u ./...
          go mod tidy
          git diff --exit-code go.???

      # - name: go mod vendor
      #   run: |
      #     go mod vendor
      #     git diff --exit-code
