# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  workflow_call:

jobs:
  # Keep same job id and name for the time being in case projects are still
  # configured to expect these specific values.
  lint_and_test_code:
    name: Lint and test using latest stable container

    # We're going to execute directly on the CI runner environment instead
    # of a container as we were before.
    runs-on: ubuntu-latest

    # It should not take longer than 5 minutes to run; realistically, one
    # minute is more than sufficient assuming that the timer starts when the
    # job is actually running (and not when the CI job is still pending an
    # available runner).
    timeout-minutes: 5

    steps:
      - name: Fail CI for dependent workflows
        run: |
          echo "This importable workflow is deprecated and will be removed soon."
          echo "See https://github.com/atc0005/shared-project-resources/issues/63 for details."
          exit 1
