# Copyright 2023 Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

# Purpose: This importable workflow is intended to act as a wrapper or bucket
# for tasks that are run on a weekly schedule. This can be used to run jobs
# that are more intensive/expensive than would be warranted to run on every
# pull request OR jobs that should be re-run periodically due to potentially
# updated data files (e.g., vulnerability scanning).

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    uses: atc0005/shared-project-resources/.github/workflows/lint-project-files.yml@master

  vulnerability:
    name: Vulnerability
    uses: atc0005/shared-project-resources/.github/workflows/vulnerability-analysis.yml@master

  go_mod_validation:
    name: Go Module Validation
    uses: atc0005/shared-project-resources/.github/workflows/go-mod-validation.yml@master

  # dependency_updates:
  #   name: Dependency Updates
  #   uses: atc0005/shared-project-resources/.github/workflows/dependency-updates.yml@master
