# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/shared-project-resources
#
# Licensed under the MIT License. See LICENSE file in the project root for
# full license information.

on:
  workflow_call:

jobs:
  govulncheck:
    # https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
    # https://github.com/golang/vuln
    # https://github.com/atc0005/go-ci/issues/734
    name: govulncheck
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      # NOTE: govulncheck is bundled within this image
      image: "ghcr.io/atc0005/go-ci:go-ci-stable"

    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.3

      # Mark the current working directory as a safe directory in git to
      # resolve "dubious ownership" complaints.
      #
      # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
      # https://confluence.atlassian.com/bbkb/git-command-returns-fatal-error-about-the-repository-being-owned-by-someone-else-1167744132.html
      # https://github.com/actions/runner-images/issues/6775
      # https://github.com/actions/checkout/issues/766
      - name: Mark the current working directory as a safe directory in git
        # run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        run: git config --global --add safe.directory "${PWD}"

      - name: Analyze source code
        run: |
          echo "govulncheck version $(go version -m $(which govulncheck) | awk '$1 == "mod" { print $3 }')"
          govulncheck -json ./...
